/*
 * This source file was generated by the Gradle 'init' task
 */
package com.eurofunk.gradle.sbom.license;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * Plugin that performs tasks regarding licenses on sbom.
 */
public class SbomLicensePlugin implements Plugin<Project> {

    public void apply(Project project) {
        project.getTasks().register("checkLicenses", CheckLicensesTask.class, (task) -> {
            task.setGroup("Reporting");
            task.setDescription("Checks licenses of dependencies in SBOM file");
        });
    }
}
